-- GENERATED by scripts/make-postgres-schema.mjs (prisma migrate diff from empty) — the Postgres baseline.
-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateTable
CREATE TABLE "Session" (
    "id" TEXT NOT NULL,
    "shop" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "isOnline" BOOLEAN NOT NULL DEFAULT false,
    "scope" TEXT,
    "expires" TIMESTAMP(3),
    "accessToken" TEXT NOT NULL,
    "userId" BIGINT,
    "firstName" TEXT,
    "lastName" TEXT,
    "email" TEXT,
    "accountOwner" BOOLEAN NOT NULL DEFAULT false,
    "locale" TEXT,
    "collaborator" BOOLEAN DEFAULT false,
    "emailVerified" BOOLEAN DEFAULT false,
    "refreshToken" TEXT,
    "refreshTokenExpires" TIMESTAMP(3),
    "adminLocale" TEXT,

    CONSTRAINT "Session_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ShopConfig" (
    "shop" TEXT NOT NULL,
    "schemaVersion" INTEGER NOT NULL,
    "data" TEXT NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ShopConfig_pkey" PRIMARY KEY ("shop")
);

-- CreateTable
CREATE TABLE "ConfigVersion" (
    "id" TEXT NOT NULL,
    "shop" TEXT NOT NULL,
    "schemaVersion" INTEGER NOT NULL,
    "data" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ConfigVersion_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "WonNode" (
    "id" TEXT NOT NULL,
    "shop" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "ruleId" TEXT,
    "discountNodeId" TEXT NOT NULL,
    "codesHash" TEXT,
    "varsVersion" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "WonNode_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "NativeDiscountBackup" (
    "id" TEXT NOT NULL,
    "shop" TEXT NOT NULL,
    "nativeId" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "snapshot" TEXT NOT NULL,
    "wonRuleId" TEXT,
    "status" TEXT NOT NULL,
    "error" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "NativeDiscountBackup_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SyncRun" (
    "id" TEXT NOT NULL,
    "shop" TEXT NOT NULL,
    "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "finishedAt" TIMESTAMP(3),
    "ok" BOOLEAN NOT NULL DEFAULT false,
    "steps" TEXT NOT NULL,
    "errorCount" INTEGER NOT NULL DEFAULT 0,
    "pending" TEXT,
    "configVersionId" TEXT,

    CONSTRAINT "SyncRun_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ShopSyncState" (
    "shop" TEXT NOT NULL,
    "timezone" TEXT,
    "productsSyncedAt" TIMESTAMP(3),
    "targetingStaleAt" TIMESTAMP(3),
    "targetingStaleNote" TEXT,
    "marketsCheckedAt" TIMESTAMP(3),
    "appliedPlan" TEXT,
    "costsScannedAt" TIMESTAMP(3),
    "costsCursor" TEXT,
    "costsPending" TEXT,
    "campaignBoundaryAt" TIMESTAMP(3),
    "campaignsFinishing" TEXT,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ShopSyncState_pkey" PRIMARY KEY ("shop")
);

-- CreateTable
CREATE TABLE "ProductTargetIndex" (
    "id" TEXT NOT NULL,
    "shop" TEXT NOT NULL,
    "productId" TEXT NOT NULL,
    "payloadHash" TEXT,
    "value" TEXT,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ProductTargetIndex_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "VariantCost" (
    "id" TEXT NOT NULL,
    "shop" TEXT NOT NULL,
    "variantId" TEXT NOT NULL,
    "productId" TEXT NOT NULL,
    "inventoryItemId" TEXT NOT NULL,
    "title" TEXT,
    "variantTitle" TEXT,
    "price" TEXT NOT NULL,
    "cost" TEXT,
    "currency" TEXT,
    "metafieldValue" TEXT,
    "mayCarry" BOOLEAN NOT NULL DEFAULT false,
    "writeError" TEXT,
    "writeFailedAt" TIMESTAMP(3),
    "scanId" TEXT,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "VariantCost_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "OutletRun" (
    "id" TEXT NOT NULL,
    "shop" TEXT NOT NULL,
    "productId" TEXT NOT NULL,
    "variantId" TEXT NOT NULL,
    "quota" INTEGER NOT NULL,
    "percent" INTEGER NOT NULL,
    "endsAt" TIMESTAMP(3),
    "priceListIds" TEXT NOT NULL DEFAULT '[]',
    "status" TEXT NOT NULL,
    "endReason" TEXT,
    "sold" INTEGER NOT NULL DEFAULT 0,
    "returned" INTEGER NOT NULL DEFAULT 0,
    "returnPending" INTEGER NOT NULL DEFAULT 0,
    "backup" TEXT,
    "sale" TEXT,
    "error" TEXT,
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "nextAttemptAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "startedAt" TIMESTAMP(3),
    "endedAt" TIMESTAMP(3),
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "OutletRun_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "OutletEvent" (
    "id" TEXT NOT NULL,
    "shop" TEXT NOT NULL,
    "runId" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "qty" INTEGER NOT NULL DEFAULT 0,
    "orderId" TEXT,
    "lineId" TEXT,
    "key" TEXT NOT NULL,
    "detail" TEXT,
    "at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "OutletEvent_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "JobState" (
    "name" TEXT NOT NULL,
    "lastRunAt" TIMESTAMP(3),
    "lastError" TEXT,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "JobState_pkey" PRIMARY KEY ("name")
);

-- CreateTable
CREATE TABLE "ShopEntitlement" (
    "shop" TEXT NOT NULL,
    "plan" TEXT NOT NULL,
    "subscriptionId" TEXT,
    "status" TEXT,
    "trialEndsAt" TIMESTAMP(3),
    "test" BOOLEAN NOT NULL DEFAULT false,
    "checkedAt" TIMESTAMP(3) NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ShopEntitlement_pkey" PRIMARY KEY ("shop")
);

-- CreateTable
CREATE TABLE "OrderDiscountFact" (
    "id" TEXT NOT NULL,
    "shop" TEXT NOT NULL,
    "orderId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL,
    "currency" TEXT NOT NULL,
    "subtotalMinor" INTEGER NOT NULL,
    "discountMinor" INTEGER NOT NULL,
    "parts" TEXT NOT NULL DEFAULT '[]',
    "gifts" INTEGER NOT NULL DEFAULT 0,
    "outletItems" INTEGER NOT NULL DEFAULT 0,
    "cancelledAt" TIMESTAMP(3),

    CONSTRAINT "OrderDiscountFact_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "ConfigVersion_shop_createdAt_idx" ON "ConfigVersion"("shop", "createdAt");

-- CreateIndex
CREATE INDEX "WonNode_shop_idx" ON "WonNode"("shop");

-- CreateIndex
CREATE UNIQUE INDEX "WonNode_shop_key_key" ON "WonNode"("shop", "key");

-- CreateIndex
CREATE INDEX "NativeDiscountBackup_shop_status_idx" ON "NativeDiscountBackup"("shop", "status");

-- CreateIndex
CREATE INDEX "SyncRun_shop_startedAt_idx" ON "SyncRun"("shop", "startedAt");

-- CreateIndex
CREATE INDEX "ProductTargetIndex_shop_idx" ON "ProductTargetIndex"("shop");

-- CreateIndex
CREATE UNIQUE INDEX "ProductTargetIndex_shop_productId_key" ON "ProductTargetIndex"("shop", "productId");

-- CreateIndex
CREATE INDEX "VariantCost_shop_inventoryItemId_idx" ON "VariantCost"("shop", "inventoryItemId");

-- CreateIndex
CREATE INDEX "VariantCost_shop_productId_idx" ON "VariantCost"("shop", "productId");

-- CreateIndex
CREATE UNIQUE INDEX "VariantCost_shop_variantId_key" ON "VariantCost"("shop", "variantId");

-- CreateIndex
CREATE INDEX "OutletRun_shop_status_idx" ON "OutletRun"("shop", "status");

-- CreateIndex
CREATE INDEX "OutletRun_shop_variantId_idx" ON "OutletRun"("shop", "variantId");

-- CreateIndex
CREATE INDEX "OutletEvent_shop_runId_at_idx" ON "OutletEvent"("shop", "runId", "at");

-- CreateIndex
CREATE UNIQUE INDEX "OutletEvent_shop_key_key" ON "OutletEvent"("shop", "key");

-- CreateIndex
CREATE INDEX "OrderDiscountFact_shop_createdAt_idx" ON "OrderDiscountFact"("shop", "createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "OrderDiscountFact_shop_orderId_key" ON "OrderDiscountFact"("shop", "orderId");

-- Partial unique index (not expressible in schema.prisma): one live claim per native discount.
CREATE UNIQUE INDEX "NativeDiscountBackup_one_claim_per_native"
    ON "NativeDiscountBackup"("shop", "nativeId") WHERE "status" IN ('moving', 'undoing');
